# Generated by Django 5.1.3 on 2024-12-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferred_activities",
            field=models.ManyToManyField(related_name="users", to="events.activity"),
        ),
    ]
