# Generated by Django 5.1.3 on 2024-11-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="fitness_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Low", "Low"),
                    ("Moderate", "Moderate"),
                    ("High", "High"),
                    ("Athlete", "Athlete"),
                ],
                default="Moderate",
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Do not show", "Do not show"),
                ],
                default="Do not show",
                max_length=11,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skill_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                    ("Expert", "Expert"),
                ],
                default="Beginner",
                max_length=12,
                null=True,
            ),
        ),
    ]
