# Generated by Django 5.1.3 on 2024-12-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="outdoor_experience",
        ),
    ]
