# Generated by Django 5.1.3 on 2024-11-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_profile_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture_upload",
            field=models.ImageField(
                blank=True,
                null=True,
                storage="storages.backends.s3boto3.S3Boto3Storage",
                upload_to="profile_pictures/",
            ),
        ),
    ]
