# Generated by Django 5.1.3 on 2024-11-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_picture_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture_upload",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
