# Generated by Django 5.1.3 on 2024-12-02 08:29

import services.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profile_picture_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture_upload",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=services.storage.DebuggableS3Storage(),
                upload_to="profile_pictures/",
            ),
        ),
    ]
